name: Packaging

on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
    - name: Create Windows Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python-version: "3.13"
        architecture: "x64"
        script: "package.py"
        artifact-name: "Windows Clock"

  mac-build:
    runs-on: macos-14
    steps:
    - name: Create Mac Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python-version: "3.13"
        architecture: "arm64"
        script: "package.py"
        artifact-name: "Mac Clock"

  linux-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Create Linux Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python-version: "3.13"
        architecture: "x64"
        script: "package.py"
        artifact-name: "Linux Clock"
