name: Packaging

on:
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Create Windows Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python_version: "3.13"
        architecture: "x64"
        script: "package.py"
        artifact_name: "Windows Clock"

  mac-build:
    runs-on: macos-latest
    steps:
    - name: Create Mac Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python_version: "3.13"
        architecture: "arm64"
        script: "package.py"
        artifact_name: "Mac Clock"

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Linux Executable
      uses: edwardkopp/run-pyinstaller-script@main
      with:
        python_version: "3.13"
        architecture: "x64"
        script: "package.py"
        artifact_name: "Linux Clock"
